Repository iterative/terraform-provider-iterative, pull requests merged in 2021-06, with the labels that each got.

#128 update banner logo & theme
  README.md
Labels: documentation

#130 Fix nil pointer dereference on SSH key parser
  iterative/utils/ssh.go
Labels: bug

#135 Hotfix/azure only reboot nvidia
  go.mod
  iterative/resource_runner.go
  iterative/resource_runner_test.go
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_invalid.golden
Labels: aws, azure, bug, p0-critical

#132 Mark startup script as sensitive
  iterative/resource_machine.go
  iterative/resource_runner.go
Labels: security

#141 Tweak readme machine example
  README.md
Labels: documentation

#134 Fix nil dereferencing on template errors
  iterative/resource_runner_test.go
Labels: bug, testing

#144 Remove ppa:graphics-drivers/ppa
  iterative/resource_runner.go
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_invalid.golden
Labels: azure, bug

#143 AWS better check and election
  iterative/aws/provider.go
  iterative/azure/provider.go
  iterative/resource_runner.go
  iterative/resource_runner_test.go
Labels: aws, enhancement
