Repository iterative/terraform-provider-iterative, pull requests merged in 2021-11, with the labels that each got.

#252 Development guide
  README.md
Labels: documentation

#256 Skip windows arm* builds
  .goreleaser.yml
Labels: bug, p0-critical

#261 Fix colons on documentation callouts
  docs/guides/getting-started.md
  docs/index.md
  docs/resources/task.md
Labels: documentation, p0-critical

#271 Mask temporary kubeconfig from logs
  .github/workflows/smoke.yml
Labels: security, testing

#274 Fix k8s test fixture
  .github/workflows/smoke.yml
Labels: bug, testing

#277 Add name to k8s test
  .github/workflows/smoke.yml
Labels: testing

#272 Fix unsafe access to event time on Azure
  task/az/resources/resource_virtual_machine_scale_set.go
Labels: bug, p1-important

#273 Wait for data to be synchronized before exiting
  task/task_test.go
Labels: bug, p0-critical, testing

#270 Turn directory tree into preformatted block
  docs/guides/getting-started.md
Labels: documentation

#283 Checkout target branch on smoke tests
  .github/workflows/smoke.yml
Labels: bug, testing

#284 Fix machine instance types
  iterative/aws/provider.go
  iterative/azure/provider.go
  iterative/gcp/provider.go
  iterative/kubernetes/provider.go
Labels: bug, p0-critical

#268 Document environment variable globbing
  docs/resources/task.md
Labels: documentation

#288 test(k8s): move test cluster to westus
  .github/workflows/smoke.yml
Labels: testing

#292 copyediting
  docs/guides/getting-started.md
  docs/index.md
  docs/resources/task.md
Labels: documentation, task

#286 make Python optional
  task/common/machine/script.go
Labels: machine-image

#296 Revert "test(k8s): move test cluster to westus"
  .github/workflows/smoke.yml
Labels: bug, testing

#248 Updates to readme
  README.md
Labels: documentation

#304 Improve identifier generation
  task/common/identifier.go
  task/common/identifier_test.go
Labels: testing

#280 Document image requirements
  docs/resources/task.md
Labels: documentation

#285 Improve release workflow
  .github/workflows/release.yml
Labels: enhancement

#310 Add golangci-lint
  .github/workflows/test.yml
  .golangci.yml
Labels: testing

#312 Handle GPG keys without intermediate GitHub Actions
  .github/workflows/release.yml
  .goreleaser.yml
Labels: security

#318 Stop machines if task script fails
  task/common/machine/script.go
Labels: bug, p1-important, task

#313 Set HOME=/root for the task script
  task/common/machine/script.go
Labels: user experience
