Repository iterative/terraform-provider-iterative, pull requests merged in 2021-08, with the labels that each got.

#179 Add Windows to the list of release targets
  .goreleaser.yml
Labels: enhancement

#170 Resource Cml runner failproof dependencies
  .restyled.yaml
  cml/clone-amis.go
  cml/setup.sh
  go.mod
  go.sum
  iterative/aws/provider.go
  iterative/azure/provider.go
  iterative/bindata.go
  iterative/resource_runner.go
  iterative/resource_runner_test.go
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_gcp.golden
  iterative/testdata/script_template_cloud_invalid.golden
  iterative/testdata/script_template_cloud_kubernetes.golden
Labels: bug

#181 Mention the Terraform JSON Configuration Syntax
  README.md
Labels: documentation
