Repository iterative/terraform-provider-iterative, pull requests merged in 2022-02, with the labels that each got.

#380 Allow custom machine+gpu*count on runner cloud=gcp
  iterative/gcp/provider.go
Labels: enhancement, cloud-gcp, runner, machine

#381 Avoid taint on apply error
  iterative/resource_task.go
Labels: bug, p0-critical

#375 Improve basic example
  README.md
  docs/guides/getting-started.md
Labels: documentation, task

#395 Separate input and output directory settings
  docs/guides/getting-started.md
  docs/resources/task.md
  iterative/resource_task.go
Labels: p1-important

#409 Simplify AMI build system
  .github/workflows/build-ami.yml
  .github/workflows/build-cml-ami.yml
  cml/ami-test.json
  cml/ami.json
  cml/clone-amis.go
  environment/README.md
  environment/ami.pkr.hcl
  environment/setup.sh
  iterative/bindata.go
  iterative/resource_runner.go
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_gcp.golden
  iterative/testdata/script_template_cloud_invalid.golden
Labels: enhancement, cloud-aws, technical debt, machine-image

#384 Add NVIDIA NGC image aliases
  task/aws/resources/data_source_image.go
  task/az/resources/resource_virtual_machine_scale_set.go
  task/gcp/resources/data_source_image.go
  task/k8s/resources/resource_job.go
Labels: machine-image, cloud-common

#406 Move task tests to AWS sandbox (OIDC)
  .github/workflows/smoke.yml
Labels: cloud-aws, security, testing, task, p2-nice-to-have

#411 Add environment to all the smoke test steps
  .github/workflows/smoke.yml
Labels: bug, testing

#402 task docs improvements
  README.md
  docs/guides/getting-started.md
  docs/index.md
  docs/resources/task.md
Labels: documentation, task
