Repository iterative/terraform-provider-iterative, pull requests merged in 2022-07, with the labels that each got.

#623 Delete .restyled.yaml
  .restyled.yaml
Labels: testing

#624 Use Go `devcontainer` and extension
  .devcontainer.json
Labels: testing

#622 keep JSON format
  iterative/utils/analytics.go
Labels: bug, technical debt

#628 Remove incompatible options from `systemd-run`
  environment/setup.sh
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_gcp.golden
  iterative/testdata/script_template_cloud_invalid.golden
Labels: bug, cloud-aws, runner
