Repository iterative/terraform-provider-iterative, pull requests merged in 2022-03, with the labels that each got.

#264 Test automatic stop mechanism
  task/az/resources/resource_virtual_machine_scale_set.go
  task/common/machine/script.go
  task/task_test.go
Labels: testing

#417 Add concurrency limit to smoke tests
  .github/workflows/smoke.yml
Labels: testing, p2-nice-to-have

#418 Create .devcontainer.json
  .devcontainer.json
Labels: enhancement, testing

#423 Logrus logs
  go.mod
  iterative/resource_task.go
  iterative/utils/logger.go
  iterative/utils/logger_test.go
  task/aws/task.go
  task/az/task.go
  task/gcp/task.go
Labels: enhancement, user experience, task

#420 Empty buckets during Delete()
  .gitignore
  task/aws/resources/resource_auto_scaling_group.go
  task/aws/resources/resource_bucket.go
  task/aws/task.go
  task/az/resources/resource_virtual_machine_scale_set.go
  task/az/task.go
  task/common/machine/storage.go
  task/gcp/resources/resource_instance_group_manager.go
  task/gcp/task.go
Labels: bug, technical debt, cloud-az, cloud-common, task

#435 task: rename `workdir.input` => `storage.workdir` & make `output` a subpath
  iterative/resource_task.go
  task/aws/task.go
  task/az/task.go
  task/common/machine/storage.go
  task/gcp/task.go
  task/k8s/task.go
  task/task.go
  task/task_test.go
Labels: enhancement, p1-important, user experience, task

#443 docs: permissions & reference roles
  docs/guides/authentication.md
  docs/guides/permissions/aws/main.tf
  docs/guides/permissions/az/main.tf
  docs/guides/permissions/gcp/main.tf
  docs/guides/permissions/k8s/kubeconfig.sh
  docs/guides/permissions/k8s/main.yml
Labels: security, cloud-common, user experience

#449 Remove dead code from cloud.go
  task/common/cloud.go
Labels: technical debt

#453 Revert #420 for `aws`
  task/aws/resources/resource_bucket.go
Labels: p0-critical, cloud-aws, cloud-common

#455 Fix `aws` bucket creation failure on `us-east-1`
  task/aws/resources/resource_bucket.go
Labels: bug, p1-important, cloud-aws

#458 Fix running CML inside CML with `pkg` binaries
  iterative/resource_runner.go
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_gcp.golden
  iterative/testdata/script_template_cloud_invalid.golden
  iterative/testdata/script_template_cloud_kubernetes.golden
  iterative/utils/helpers.go
Labels: bug, runner

#460 Destroy instance if runner does not sync
  iterative/resource_runner.go
Labels: enhancement, runner

#463 Add user-oriented file transfer logs
  docs/guides/getting-started.md
  go.mod
  go.sum
  task/common/machine/storage.go
Labels: enhancement, user experience

#467 Display real-time progress while transferring data
  task/common/machine/storage.go
Labels: enhancement, user experience

#466 Avoid `rclone` error message on task logs
  task/common/machine/script.go
Labels: enhancement, user experience

#471 Improve TF_LOG_PROVIDER logs
  go.mod
  go.sum
  iterative/utils/logger.go
  iterative/utils/logger_test.go
  task/aws/task.go
  task/az/task.go
  task/gcp/task.go
  task/k8s/task.go
Labels: user experience

#479 Increase data transfer progress interval to 10 s
  task/common/machine/storage.go
Labels: enhancement

#475 Document `name` and `id`
  docs/guides/getting-started.md
  docs/resources/task.md
Labels: documentation
