Repository iterative/terraform-provider-iterative, pull requests merged in 2022-09, with the labels that each got.

#649 Fix identities on Microsoft Azure runners
  iterative/azure/provider.go
Labels: bug, p0-critical, cloud-az, resource-runner, resource-machine

#654 Print identifier before creating resources
  cmd/create/create.go
Labels: enhancement, ui/ux

#653 Implement human-readable random identifier generation
  cmd/create/create.go
  go.mod
  go.sum
  iterative/resource_task.go
  task/common/identifier.go
  task/common/identifier_test.go
  task/task.go
  task/task_smoke_test.go
Labels: enhancement, ui/ux

#655 Simplify command-line tool output format
  cmd/create/create.go
  cmd/list/list.go
  cmd/read/read.go
  cmd/root.go
  go.mod
  go.sum
  task/common/machine/machine-script.sh.tpl
  task/common/machine/testdata/machine_script_full.golden
  task/common/machine/testdata/machine_script_minimal.golden
  task/common/steps.go
Labels: enhancement, ui/ux

#656 Fix k8s tag propagation and controller-uid detection
  cmd/create/create.go
  iterative/kubernetes/provider.go
  task/aws/task.go
  task/az/resources/resource_virtual_machine_scale_set.go
  task/az/task.go
  task/common/values.go
  task/gcp/task.go
  task/k8s/resources/resource_job.go
  task/k8s/task.go
Labels: bug, technical debt, cloud-common, resource-task, cloud-k8s, standalone-binary

#657 Use `region` field as comma-delimited node selector for k8s
  docs/resources/task.md
  task/k8s/resources/resource_job.go
Labels: ui/ux, resource-task, cloud-k8s

#670 Automate AWS availability zone selection
  iterative/aws/provider.go
Labels: enhancement, cloud-aws, resource-runner, resource-machine, external-request

#672 Improve test and release workflows
  .github/workflows/build-ami.yml
  .github/workflows/release.yml
  .github/workflows/smoke.yml
  .github/workflows/test.yml
  .goreleaser.yml
  go.mod
  go.sum
Labels: technical-debt, testing, releases

#676 Fix smoke test script preamble
  task/task_smoke_test.go
Labels: technical-debt, testing, p2-nice-to-have

#677 Consolidate release workflow
  .github/workflows/release.yml
  .goreleaser.yml
Labels: enhancement, technical-debt, releases

#678 Move AKS tests to `Standard_NC4as_T4_v3`
  .github/workflows/smoke.yml
Labels: technical-debt, cloud-az, testing, cloud-k8s, gpu

#683 Migrate `k8s` smoke test after quota increase approval
  .github/workflows/smoke.yml
Labels: testing, cloud-k8s

#685 Revert OIDC changes for `az` tests
  .github/workflows/smoke.yml
Labels: technical-debt, cloud-az, testing
