Repository iterative/terraform-provider-iterative, pull requests merged in 2022-08, with the labels that each got.

#631 `task` Fix id-generation
  task/common/identifier.go
  task/common/identifier_test.go
Labels: bug, p0-critical, cloud-common, task, external-request

#635 Use go build tags to separate task smoke tests
  .github/workflows/build-ami.yml
  .github/workflows/release.yml
  .github/workflows/smoke.yml
  Makefile
  task/task_smoke_test.go
Labels: testing, task

#636 Fix failing UserId test
  iterative/utils/analytics.go
  iterative/utils/analytics_test.go
Labels: testing

#639 Parse nested maps from viper configuration
  cmd/create/create.go
  cmd/root.go
Labels: bug, ui/ux, resource-task

#642 Slight refactoring of machine script generation
  task/aws/resources/data_source_credentials.go
  task/aws/resources/resource_launch_template.go
  task/aws/task.go
  task/az/resources/data_source_credentials.go
  task/az/resources/resource_virtual_machine_scale_set.go
  task/az/task.go
  task/common/machine/machine-script.sh.tpl
  task/common/machine/script.go
  task/common/machine/script_test.go
  task/common/machine/testdata/machine_script_full.golden
  task/common/machine/testdata/machine_script_minimal.golden
  task/gcp/resources/data_source_credentials.go
  task/gcp/resources/resource_instance_template.go
  task/gcp/task.go
Labels: technical debt, testing

#643 Use named fields instead of anonymous fields in common.Task
  task/common/values.go
Labels: technical debt

#597 Added indexed option for k8s jobs
  task/k8s/resources/resource_job.go
Labels: external-request

#632 Add support for instance-permission-set in azure
  cmd/create/create.go
  docs/resources/task.md
  iterative/azure/provider.go
  iterative/resource_machine.go
  task/aws/resources/data_source_permission_set.go
  task/az/resources/data_source_permission_set.go
  task/az/resources/data_source_permission_set_test.go
  task/az/task.go
Labels: cloud-az

#646 add gcr/gcp docker helper
  environment/setup.sh
  iterative/testdata/script_template_cloud_aws.golden
  iterative/testdata/script_template_cloud_azure.golden
  iterative/testdata/script_template_cloud_gcp.golden
  iterative/testdata/script_template_cloud_invalid.golden
Labels: enhancement, cloud-gcp, resource-runner

#645 Restructure how resource allocation/deallocation/read steps are defined and executed
  task/aws/resources/resource_bucket.go
  task/aws/task.go
  task/az/task.go
  task/common/steps.go
  task/common/steps_test.go
  task/gcp/task.go
  task/k8s/task.go
Labels: enhancement, technical debt
