Repository iterative/terraform-provider-iterative, pull requests merged in 2022-05, with the labels that each got.

#551 Bump go-getter
  go.mod
  go.sum
Labels: technical debt, security, p2-nice-to-have

#553 Port `github.ref_name` to smoke.yml
  .github/workflows/smoke.yml
Labels: testing, p2-nice-to-have

#554 Escape dots in GCP OIDC regular expression
  iterative/gcp/provider.go
Labels: security, p2-nice-to-have

#557 Simplify Readme
  README.md
  docs/guides/authentication.md
  docs/guides/getting-started.md
Labels: documentation

#567 Fix data synchronization logs
  iterative/utils/logger.go
  task/common/machine/storage.go
Labels: bug, p0-critical, task

#568 Fix NVIDIA APT GPG keys
  task/common/machine/script.go
Labels: bug, task

#573 add example projects/blogs
  README.md
  docs/guides/authentication.md
  docs/index.md
Labels: documentation, task

#578 Reconcile loggers
  iterative/resource_task.go
  iterative/utils/logger.go
  iterative/utils/logger_test.go
Labels: bug, cloud-common, UX, task, logs

#583 Separate credentials from other environment variables
  task/aws/resources/resource_launch_template.go
  task/az/resources/resource_virtual_machine_scale_set.go
  task/common/machine/script.go
  task/gcp/resources/resource_instance_template.go
Labels: enhancement, cloud-aws, cloud-az, security, cloud-gcp

#588 Fix stray brackets on status messages
  iterative/utils/logger.go
Labels: UX, task, logs

#589 new dark/light sequel
  README.md
Labels: documentation

#587 Use global timeout on `aws`, `az` & `gcp`
  task/common/machine/script.go
  task/common/machine/storage.go
Labels: enhancement, cloud-aws, technical debt, cloud-az, cloud-gcp, task

#592 Avoid pinning `aws` GPU images to a specific date
  task/aws/resources/data_source_image.go
Labels: cloud-aws, machine-image, task

#596 Increase smoke test frequency to daily
  .github/workflows/smoke.yml
Labels: testing, cloud-common, task
